LOG_TYPE=console
LOG_FILE_PATH=/root/projects/logs/capofpro.log
LOG_LEVEL=info
MYSQL_DATABASE=capofpro
MYSQL_PASSWORD=1qaz2wsx
WEB_PORT=3006

APP_DEFAULT_LLM_MODEL=qwen-turbo-latest
APP_LLM_BAILIAN_API_KEY=sk-
APP_LLM_VOLCENGINE_API_KEY=
APP_STORAGE_ROOT=
APP_CHROME_PATH=/usr/bin/google-chrome
APP_CHROME_DRIVER_PATH=
APP_TEMP_FOLDER_ROOT=
